#!/usr/bin/env bash

ROOT_DIR=$PWD
SKIA_OUT="${ROOT_DIR}/out"

PREBUILT_DIR="${ROOT_DIR}/prebuilt"
BUILD_ARGS='cc="clang" cxx="clang++" is_debug=false is_official_build=true skia_use_system_libjpeg_turbo=false skia_use_system_libwebp=false skia_use_system_libpng=false skia_use_system_harfbuzz=false skia_use_system_expat=false extra_cflags_cc=["-frtti"]'

case "$(uname -s)" in
    Linux*)
        PREBUILT_DIR="${PREBUILT_DIR}/linux.amd64"
        BUILD_ARGS="${BUILD_ARGS} skia_use_system_icu=true"
        ;;
    Darwin*)
        PREBUILT_DIR="${PREBUILT_DIR}/darwin.amd64"
        BUILD_ARGS="${BUILD_ARGS} skia_use_system_icu=false"
        ;;
    *)
        echo "Unknown OS"
        exit 1
        ;;
esac

if [ ! -d "$SKIA_OUT" ]; then
    mkdir $SKIA_OUT
fi

cd $SKIA_OUT

if [ ! -d "depot_tools" ]; then
    git clone --depth 1 'https://chromium.googlesource.com/chromium/tools/depot_tools.git'
fi
export PATH="$PWD/depot_tools:$PATH"

if [ ! -d "skia" ]; then
    git clone --depth 1 -b chrome/m85 'https://github.com/google/skia'
fi

cd skia

python2 tools/git-sync-deps
bin/gn gen out --args="${BUILD_ARGS}"
ninja -C out skia

cp out/libskia.a out/libpng.a $PREBUILT_DIR
